spring:
  datasource:
    url: ${vcap.services.ultra_db.credentials.uri:jdbc:mysql://localhost:3306/ultra_db?user=root&password=root&useSSL=false&serverTimezone=UTC}
  jpa:
    database: MYSQL
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
